meta_system = "You a prompt engineeer."


meta_user = """Write a prompt that instructs a language model to determine if an appended piece of text was written by AI or not. Do not introduce the prompt or add other formatting. I will append the text to your prompt with a label.

Instruct the model to determine if the probability that the the response was written by AI as either "very unlikely", "unlikely", "equally likely and unlikely", "likely", or "very likely".
Tell the model to provide an analysis and probability in JSON format. For example: 

{
  "analysis": "The text contains onversational style and mistakes. There is insoncistency to the structure.",
  "probability generated by AI": "unlikely"
}
"""

good_prompt_example = """
1. Read the text thoroughly and consider its overall structure, coherence, and flow.

2. Pay attention to the following factors that may indicate whether the text is AI-generated or human-written:

   a) Language complexity and variety: Human writing often has more varied sentence structures and vocabulary.
   b) Contextual understanding: Humans are generally better at maintaining context throughout a piece of writing.
   c) Emotional nuance: Human writing tends to convey emotions and subjective perspectives more naturally.
   d) Errors and inconsistencies: Human writing may contain more natural errors or typos, while AI text might have more consistent patterns or unusual errors.
   e) Creativity and originality: Humans often produce more creative and original content.
   f) Personal anecdotes or specific examples: Human writers are more likely to include personal experiences or detailed examples.
   g) Logical flow and argumentation: Human writing might have more nuanced or complex logical structures.

3. Analyze the text based on these factors and any other relevant observations you make.

4. Provide a detailed explanation of your reasoning, citing specific examples from the text that support your conclusion. Include this explanation within <reasoning> tags.

5. Based on your analysis, make a final determination on whether the text was likely generated by an AI or written by a human. Express your conclusion as a percentage likelihood that the text is AI-generated (e.g., 75% likely to be AI-generated). Include your final determination within <determination> tags.

Remember to be thorough in your analysis and provide clear justifications for your conclusion.
"""
separator = "### ESSAY SUBMISSION ###"
task_system = 'You are a grading assistant. Your job is to determine if an essay was written by essay.'
label_name = 'probability generated by AI'
evaluator_prompt = ''
