detector_system = """Your job is to detect if text was written by a language model. You will be given a writing prompt and a response. Determine if the the response was written by a language model
Analyze the response and determine the likelihood that it was written by an AI language model rather than a human. In your analysis, consider factors such as writing style, coherence, depth of insight, use of examples, repetition, and any patterns typical of AI-generated text. Provide a detailed explanation supporting your conclusion."""

detector_user = """Determine if the  likelihood that the the response was written by AI as either "very unlikely", "unlikely", "equally likely and unlikely", "likely", or "very likely".
Put your analysis and likelihood in JSON format. For example: 

{{
  "analysis": "The text contains onversational style and mistakes. There is insoncistency to the structure.",
  "likelihood generated by AI": "unlikely"
}}

### WRITING PROMPT ###
{}

### RESPONSE ###
{}
"""

prompt_writer_system = "You are a prompt engineer."
prompt_writer_user = """Write instructions for a language model to assess if a response was written by AI or by a human. The model will be given your instructions, a writing prompt and a response to that writing prompt.
Instruct the model to assess the response.
"""

claude_improved_prompt = """You are tasked with determining whether the following text was generated by an AI or written by a human. Analyze the text carefully and consider various factors that might indicate its origin.

Here is the text to analyze:
<text_to_analyze>
{}
</text_to_analyze>

To make your determination, follow these steps:

1. Read the text thoroughly and consider its overall structure, coherence, and flow.

2. Pay attention to the following factors that may indicate whether the text is AI-generated or human-written:

   a) Language complexity and variety: Human writing often has more varied sentence structures and vocabulary.
   b) Contextual understanding: Humans are generally better at maintaining context throughout a piece of writing.
   c) Emotional nuance: Human writing tends to convey emotions and subjective perspectives more naturally.
   d) Errors and inconsistencies: Human writing may contain more natural errors or typos, while AI text might have more consistent patterns or unusual errors.
   e) Creativity and originality: Humans often produce more creative and original content.
   f) Personal anecdotes or specific examples: Human writers are more likely to include personal experiences or detailed examples.
   g) Logical flow and argumentation: Human writing might have more nuanced or complex logical structures.

3. Analyze the text based on these factors and any other relevant observations you make.

4. Provide a detailed explanation of your reasoning, citing specific examples from the text that support your conclusion. Include this explanation within <reasoning> tags.

5. Based on your analysis, make a final determination on whether the text was likely generated by an AI or written by a human. Express your conclusion as a percentage likelihood that the text is AI-generated (e.g., 75% likely to be AI-generated). Include your final determination within <determination> tags.

Remember to be thorough in your analysis and provide clear justifications for your conclusion.
"""
